### ISSUE TITLE
Add Keyboard shortcut to scale shapes proportionally

### ISSUE THREAD

**Issue by tyt2y3** [mattlag/Glyphr-Studio-Help#7]
I tried holding ctrl, shift and alt while scrolling, but none works

**Comment by tyt2y3** [comment]
okay. I found it out. I have to go to the attributes panel and click lock aspect ratio
![image](https://user-images.githubusercontent.com/1782664/31825530-1ec43c20-b5e5-11e7-8860-a3f46dcecaf0.png)

**Comment by mattlag** [comment]
This is a great idea, there is no keyboard shortcut for this today - I will add it!

**Comment by mattlag** [comment]
Moving this idea to Glyphr Studio v2
