### ISSUE TITLE
Contextual forms

### ISSUE THREAD

**Issue by EbrahimKaram** [mattlag/Glyphr-Studio-Help#8]
I was trying to edit a syrianic type font on your platform
SyrCOMJerusalem
It's an otf file. 
However, everytime I we export the font back after edits we lose the contextual glyphs. These are the glyphs that depend on the position of the word. This is usually common in Aramaic languages such as Hebrew, Syriac, and Arabic. 

In the test drive option of the app, it seems that we can't get the other glyphs as well

**Comment by mattlag** [comment]
Hello!

Unfortunately, Glyphr Studio can't import contextual glyphs, or ligatures.
You can design ligatures in Glyphr Studio, and export them, but they cannot
be imported from existing fonts.

Sorry, let me know if you have any other questions!
